[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gbce_simple_stock_market"
version = "0.1.0"
description = "A simple stock market application for calculating GBCE indices."
authors = [{name = "Javier", email = "your.email@example.com"}]
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["stock market", "finance", "GBCE", "index"]
classifiers = [
    "Programming Language :: Python :: 3.9",
]
dependencies = [  # List your project's dependencies
    # Example:
    # "requests>=2.28.1",
    # "numpy>=1.24.0"
]

[tool.setuptools]
packages = ["gbce_simple_stock_market"] # Replace with the actual name of your package/module

[tool.pytest.ini_options] # Configuration for pytest (if you use it)
testpaths = ["tests"]  # Directory where your tests are located
